[theme]
base = "light"
primaryColor = "#0B7285"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F1F3F5"
textColor = "#1F2937"
font = "sans serif"

[server]
runOnSave = true

[browser]
gatherUsageStats = false
